//	Header generated by Constructor for Palm OS (R) 1.9
//
//	Generated at 21:41:58  on 15 Декабрь 2005 г.
//
//	Generated for file: starter.prc
//
//	THIS IS AN AUTOMATICALLY GENERATED HEADER FILE
//	DO NOT EDIT - CHANGES MADE TO THIS FILE WILL BE LOST
//
//	Palm App Name:   		"PACE Native Starter"
//
//	Palm App Version:		"1.0"


//	Resource: tFRM 9996
#define StarterAppForm                            9996	//(Left Origin = 0, Top Origin = 0, Width = 160, Height = 160, Usable = 1, Modal = 0, Save Behind = 0, Help ID = 0, Menu Bar ID = 9998, Default Button ID = 0)

//	Resource: tFRM 9995
#define AboutStarterForm                          9995	//(Left Origin = 2, Top Origin = 2, Width = 156, Height = 156, Usable = 1, Modal = 1, Save Behind = 1, Help ID = 0, Menu Bar ID = 0, Default Button ID = 0)
#define AboutStarterStarterLabel                  9994	//(Left Origin = 61, Top Origin = 23, Usable = 1, Font = Large)
#define AboutStarterUsethisapplicationasastartLabel 9993	//(Left Origin = 23, Top Origin = 54, Usable = 1, Font = Standard)
#define AboutStarterVersion10Label                9992	//(Left Origin = 50, Top Origin = 104, Usable = 1, Font = Bold)
#define AboutStarterOKButton                      9991	//(Left Origin = 58, Top Origin = 133, Width = 40, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)


//	Resource: Talt 9990
#define SystemIncompatibleAlert                   9990
#define SystemIncompatibleOK                      0


//	Resource: MBAR 9998
#define OptionsMenuBar                            9998


//	Resource: MENU 9998
#define OptionsMenu                               9997
#define OptionsAboutStarterAppID9997              9997


//	Resource: PICT 1000
#define k22x22monochromeBitmap                    1000

//	Resource: PICT 1001
#define k22x224graysBitmap                        1001

//	Resource: PICT 1002
#define k22x22256colorsBitmap                     1002

//	Resource: PICT 1003
#define k44x44monochromeBitmap                    1003

//	Resource: PICT 1004
#define k44x444graysBitmap                        1004

//	Resource: PICT 1005
#define k44x44256colorsBitmap                     1005

//	Resource: PICT 1006
#define k15x9monochromeBitmap                     1006

//	Resource: PICT 1007
#define k15x94graysBitmap                         1007

//	Resource: PICT 1008
#define k15x9256colorsBitmap                      1008

//	Resource: PICT 1009
#define k30x18monochromeBitmap                    1009

//	Resource: PICT 1010
#define k30x184graysBitmap                        1010

//	Resource: PICT 1011
#define k30x18256colorsBitmap                     1011


//	Resource: taif 1000
#define Large6depthsAppIconFamily                 1000

//	Resource: taif 1001
#define Small6depthsAppIconFamily                 1001

